language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: nWmZTOhT8yGuDdtR+0ZsHmjPiit9WXDu5xnoJBkAqXQUKEn1qYhLEBirB7OSM6PRSULDQq9WX57bJmjJ6Ra/kQah6yYwyvLZHIv5UmXcL7JsmLjIyh+epIDWnPVEYJ5B3oDSvxwv8/18zV0XcOwf6q8c3vkHgQe7eBUHX5+SW8o=
